export const division_office = [
    { id: 1, value: 'OFFICE OF THE SCHOOLS DIVISION SUPERINTENDENT (OSDS)' },
    { id: 2, value: 'SCHOOL GOVERNANCE AND OPERATIONS DIVISION (SGOD)' },
    { id: 3, value: 'CURRICULUM IMPLEMENTATION DIVISION (CID)' },
]

export const division_positions = [
    { id: 1, value: "ACCOUNTANT III" },
    { id: 2, value: "ADMINISTRATIVE AIDE I" },
    { id: 3, value: "ADMINISTRATIVE AIDE II" },
    { id: 4, value: "ADMINISTRATIVE AIDE III" },
    { id: 5, value: "ADMINISTRATIVE AIDE IV" },
    { id: 6, value: "ADMINISTRATIVE AIDE V" },
    { id: 7, value: "ADMINISTRATIVE AIDE VI" },
    { id: 8, value: "ADMINISTRATIVE ASSISTANT I" },
    { id: 9, value: "ADMINISTRATIVE ASSISTANT II" },
    { id: 10, value: "ADMINISTRATIVE ASSISTANT III" },
    { id: 11, value: "ADMINISTRATIVE OFFICER I" },
    { id: 12, value: "ADMINISTRATIVE OFFICER II" },
    { id: 13, value: "ADMINISTRATIVE OFFICER III" },
    { id: 14, value: "ADMINISTRATIVE OFFICER IV" },
    { id: 15, value: "ADMINISTRATIVE OFFICER V" },
    { id: 16, value: "ASSISTANT SCHOOLS DIVISION SUPERINTENDENT" },
    { id: 17, value: "ATTORNEY III" },
    { id: 18, value: "CHIEF EDUCATION SUPERVISOR" },
    { id: 19, value: "DENTIST II" },
    { id: 20, value: "EDUCATION PROGRAM SPECIALIST II" },
    { id: 21, value: "EDUCATION PROGRAM SUPERVISOR" },
    { id: 22, value: "ENGINEER III" },
    { id: 23, value: "INFORMATION TECHNOLOGY OFFICER I" },
    { id: 24, value: "LIBRARIAN II" },
    { id: 25, value: "NURSE II" },
    { id: 26, value: "PLANNING OFFICER III" },
    { id: 27, value: "PROJECT DEVELOPMENT OFFICER I" },
    { id: 28, value: "PROJECT DEVELOPMENT OFFICER II" },
    { id: 29, value: "PUBLIC SCHOOLS DISTRICT SUPERVISOR" },
    { id: 30, value: "SCHOOL LIBRARIAN III" },
    { id: 31, value: "SCHOOLS DIVISION SUPERINTENDENT" },
    { id: 32, value: "SENIOR EDUCATION PROGRAM SPECIALIST" },
    { id: 33, value: "LOCAL SCHOOL BOARD (LSB)" },
    { id: 34, value: "OTHERS" },
];


export const division_station = [
    { id: 1, value: 'DIVISION OFFICE PROPER' },
    { id: 2, value: 'ELEMENTARY SCHOOL' },
    { id: 3, value: 'INTEGRATED SCHOOL (ELEM & JHS)' },
    { id: 4, value: 'SECONDARY SCHOOL (JHS)' },
    { id: 5, value: 'SECONDARY SCHOOL (JHS & SHS)' },
    { id: 6, value: 'SECONDARY SHS (Stand Alone)' },
]


export const division_schools = [
    { id: 1, value: "ACACIA ELEM SCHOOL" },
    { id: 2, value: "AMANG RODRIGUEZ ELEM SCHOOL" },
    { id: 3, value: "BAGONG LOTE ELEM SCHOOL" },
    { id: 4, value: "CATMON INTEGRATED SCHOOL ELEM" },
    { id: 5, value: "COL RAMON CAMUS INTEGRATED SCHOOL ELEM" },
    { id: 6, value: "CONCEPCION ELEM SCHOOL" },
    { id: 7, value: "DAMPALIT I ELEM SCHOOL" },
    { id: 8, value: "DAMPALIT INTEGRATED SCHOOL" },
    { id: 9, value: "DELA PAZ ELEM SCHOOL" },
    { id: 10, value: "E DELOS SANTOS ELEM SCHOOL" },
    { id: 11, value: "GUILLERMO S. SANCHEZ MES" },
    { id: 12, value: "IMELDA ELEMENTARY SCHOOL" },
    { id: 13, value: "LONGOS ELEMENTARY SCHOOL" },
    { id: 14, value: "MALABON ELEMENTARY SCHOOL" },
    { id: 15, value: "MAYSILO ELEMENTARY SCHOOL" },
    { id: 16, value: "MUZON ELEMENTARY SCHOOL" },
    { id: 17, value: "NINOY AQUINO ELEMENTARY SCHOOL" },
    { id: 18, value: "NIUGAN ELEMENTARY SCHOOL" },
    { id: 19, value: "PANGHULO ELEMENTARY SCHOOL" },
    { id: 20, value: "PANGHULO ELEMENTARY SCHOOL I" },
    { id: 21, value: "POTRERO ELEMENTARY SCHOOL" },
    { id: 22, value: "POTRERO ELEMENTARY SCHOOL I" },
    { id: 23, value: "SANTIAGO SYJUCO MES" },
    { id: 24, value: "SANTULAN ELEMENTARY SCHOOL" },
    { id: 25, value: "TAÑONG ELEMENTARY SCHOOL I" },
    { id: 26, value: "TAÑONG INTEGRATED SCHOOL" },
    { id: 27, value: "TINAJEROS ELEMENTARY SCHOOL" },
    { id: 28, value: "TONSUYA ELEMENTARY SCHOOL" },
    { id: 29, value: "ACACIA NATL HIGH SCHOOL JHS" },
    { id: 30, value: "CATMON INTEGRATED SCHOOL JHS" },
    { id: 31, value: "COL RAMON CAMUS INTEGRATED SCHOOL JHS" },
    { id: 32, value: "CONCEPCION TVS" },
    { id: 33, value: "DAMPALIT IS" },
    { id: 34, value: "IMELDA ISS" },
    { id: 35, value: "LONGOS NHS" },
    { id: 36, value: "MALABON CITY SCIENCE & MATHEMATICS NHS" },
    { id: 37, value: "MALABON NHS" },
    { id: 38, value: "PANGHULO NHS" },
    { id: 39, value: "POTRERO NHS" },
    { id: 40, value: "SANTIAGO SYJUCO MISS" },
    { id: 41, value: "TAÑONG IS" },
    { id: 42, value: "TAÑONG NHS" },
    { id: 43, value: "TINAJEROS NHS" },
    { id: 44, value: "TUGATOG NHS" },
    { id: 45, value: "MALABON CITY TECH VOC AND ENTREPRENEURSHIP SHS" },
    { id: 46, value: "MALABON NATL HIGH SCHOOL SHS" },
    { id: 47, value: "NINOY AQUINO SENIOR HIGH SCHOOL" },
];


export const divison_hours = [
    { id: 1, value: "4 hours" },
    { id: 2, value: "5 hours" },
    { id: 3, value: "6 hours" },
    { id: 4, value: "7 hours" },
    { id: 5, value: "8 hours" },
    { id: 6, value: "12 hours" },
    { id: 7, value: "16 hours" },
    { id: 8, value: "20 hours" },
    { id: 9, value: "24 hours" },
    { id: 10, value: "28 hours" },
    { id: 11, value: "32 hours" },
    { id: 12, value: "36 hours" },
    { id: 13, value: "40 hours" },
    { id: 14, value: "44 hours" },
    { id: 15, value: "48 hours" },
    { id: 16, value: "52 hours" },
    { id: 17, value: "56 hours" },
    { id: 18, value: "60 hours" },
    { id: 19, value: "64 hours" },
    { id: 20, value: "68 hours" },
    { id: 21, value: "72 hours" },
    { id: 22, value: "76 hours" },
    { id: 23, value: "80 hours" },
    { id: 24, value: "84 hours" },
    { id: 25, value: "88 hours" },
    { id: 26, value: "92 hours" },
    { id: 27, value: "96 hours" },
    { id: 28, value: "100 hours" },
    { id: 29, value: "104 hours" },
    { id: 30, value: "108 hours" },
    { id: 31, value: "112 hours" },
    { id: 32, value: "116 hours" },
    { id: 33, value: "120 hours" },
];


export const divison_conductedBy = [
    { id: 1, value: "School" },
    { id: 2, value: "Division Office" },
    { id: 3, value: "Regional Office" },
    { id: 4, value: "Central Office" },
    { id: 5, value: "Learning Service Provider" },
    { id: 6, value: "Others" },
];

export const divison_classification = [
    { id: 1, value: "Non-Teaching" },
    { id: 2, value: "Related Teaching" },
];

export const division_years_of_service = [
    { id: 1, value: '1' },
    { id: 2, value: '2' },
    { id: 3, value: '3' },
    { id: 4, value: '4' },
    { id: 5, value: '5' },
    { id: 6, value: '6' },
    { id: 7, value: '7' },
    { id: 8, value: '8' },
    { id: 9, value: '9' },
    { id: 10, value: '10' },
    { id: 11, value: '11' },
    { id: 12, value: '12' },
    { id: 13, value: '13' },
    { id: 14, value: '14' },
    { id: 15, value: '15' },
    { id: 16, value: '16' },
    { id: 17, value: '17' },
    { id: 18, value: '18' },
    { id: 19, value: '19' },
    { id: 20, value: '20' },
    { id: 21, value: '21' },
    { id: 22, value: '22' },
    { id: 23, value: '23' },
    { id: 24, value: '24' },
    { id: 25, value: '25' },
    { id: 26, value: '26' },
    { id: 27, value: '27' },
    { id: 28, value: '28' },
    { id: 29, value: '29' },
    { id: 30, value: '30' },
    { id: 31, value: '31' },
    { id: 32, value: '32' },
    { id: 33, value: '33' },
    { id: 34, value: '34' },
    { id: 35, value: '35' },
    { id: 36, value: '36' },
    { id: 37, value: '37' },
    { id: 38, value: '38' },
    { id: 39, value: '39' },
    { id: 40, value: '40' }
];


export const division_unitsArray = [
    { id: 1, value: "ACCOUNTING" },
    { id: 2, value: "ADMINISTRATIVE" },
    { id: 3, value: "ALS" },
    { id: 4, value: "BUDGET" },
    { id: 5, value: "CASH" },
    { id: 6, value: "CID" },
    { id: 7, value: "DRRM" },
    { id: 8, value: "ENGINEERING" },
    { id: 9, value: "HEALTH AND NUTRITION" },
    { id: 10, value: "HUMAN RESOURCE DEVELOPMENT" },
    { id: 11, value: "HUMAN RESOURCE MANAGEMENT" },
    { id: 12, value: "ICT" },
    { id: 13, value: "LEGAL" },
    { id: 14, value: "OASDS" },
    { id: 15, value: "OSDS" },
    { id: 16, value: "PROPERTY AND SUPPLY" },
    { id: 17, value: "RECORDS" },
    { id: 18, value: "SCHOOL MANAGEMENT MONITORING AND EVALUATION" },
    { id: 19, value: "SOCIAL MOBILIZATION AND NETWORKING" },
    { id: 20, value: "YOUTH FORMATION DEVELOPMENT" }
];


export const divsion_years = [
    { id: 1, value: '2022' },
    { id: 2, value: '2021' },
    { id: 3, value: '2020' },
    { id: 4, value: '2019' }
];
