export const school_positions = [
    { id: 1, value: "ADMINISTRATIVE AIDE I" },
    { id: 2, value: "ADMINISTRATIVE AIDE II" },
    { id: 3, value: "ADMINISTRATIVE AIDE III" },
    { id: 4, value: "ADMINISTRATIVE AIDE IV" },
    { id: 5, value: "ADMINISTRATIVE AIDE V" },
    { id: 6, value: "ADMINISTRATIVE AIDE VI" },
    { id: 7, value: "ADMINISTRATIVE ASSISTANT I" },
    { id: 8, value: "ADMINISTRATIVE ASSISTANT II" },
    { id: 9, value: "ADMINISTRATIVE ASSISTANT III" },
    { id: 10, value: "ADMINISTRATIVE OFFICER I" },
    { id: 11, value: "ADMINISTRATIVE OFFICER II" },
    { id: 12, value: "ADMINISTRATIVE OFFICER III" },
    { id: 13, value: "ASSISTANT SCHOOL PRINCIPAL I" },
    { id: 14, value: "ASSISTANT SCHOOL PRINCIPAL II" },
    { id: 15, value: "GUIDANCE COUNSELOR I" },
    { id: 16, value: "GUIDANCE COUNSELOR II" },
    { id: 17, value: "GUIDANCE COUNSELOR III" },
    { id: 18, value: "HEAD TEACHER I" },
    { id: 19, value: "HEAD TEACHER II" },
    { id: 20, value: "HEAD TEACHER III" },
    { id: 21, value: "HEAD TEACHER IV" },
    { id: 22, value: "HEAD TEACHER V" },
    { id: 23, value: "HEAD TEACHER VI" },
    { id: 24, value: "MASTER TEACHER I" },
    { id: 25, value: "MASTER TEACHER II" },
    { id: 26, value: "REGISTRAR I" },
    { id: 27, value: "SCHOOL LIBRARIAN III" },
    { id: 28, value: "SCHOOL PRINCIPAL I" },
    { id: 29, value: "SCHOOL PRINCIPAL II" },
    { id: 30, value: "SCHOOL PRINCIPAL III" },
    { id: 31, value: "SCHOOL PRINCIPAL IV" },
    { id: 32, value: "SPECIAL EDUCATION TEACHER I" },
    { id: 33, value: "SPECIAL SCIENCE TEACHER I" },
    { id: 34, value: "TEACHER I" },
    { id: 35, value: "TEACHER II" },
    { id: 36, value: "TEACHER III" },
    { id: 37, value: "LOCAL SCHOOL BOARD (LSB)" },
    { id: 38, value: "OTHERS (Please Specify)" }
];

export const school_stations = [
    { id: 1, value: "ELEMENTARY SCHOOL" },
    { id: 2, value: "INTEGRATED SCHOOL (ELEM & JHS)" },
    { id: 3, value: "SECONDARY SCHOOL (JHS)" },
    { id: 4, value: "SECONDARY SCHOOL (JHS & SHS)" },
    { id: 5, value: "SECONDARY SHS (Stand Alone)" }
];

export const schools = [
    { id: 1, value: "ACACIA ELEM SCHOOL" },
    { id: 2, value: "AMANG RODRIGUEZ ELEM SCHOOL" },
    { id: 3, value: "BAGONG LOTE ELEM SCHOOL" },
    { id: 4, value: "CATMON INTEGRATED SCHOOL ELEM" },
    { id: 5, value: "COL RAMON CAMUS INTEGRATED SCHOOL ELEM" },
    { id: 6, value: "CONCEPCION ELEM SCHOOL" },
    { id: 7, value: "DAMPALIT I ELEM SCHOOL" },
    { id: 8, value: "DAMPALIT INTEGRATED SCHOOL" },
    { id: 9, value: "DELA PAZ ELEM SCHOOL" },
    { id: 10, value: "E DELOS SANTOS ELEM SCHOOL" },
    { id: 11, value: "GUILLERMO S. SANCHEZ MES" },
    { id: 12, value: "IMELDA ELEMENTARY SCHOOL" },
    { id: 13, value: "LONGOS ELEMENTARY SCHOOL" },
    { id: 14, value: "MALABON ELEMENTARY SCHOOL" },
    { id: 15, value: "MAYSILO ELEMENTARY SCHOOL" },
    { id: 16, value: "MUZON ELEMENTARY SCHOOL" },
    { id: 17, value: "NINOY AQUINO ELEMENTARY SCHOOL" },
    { id: 18, value: "NIUGAN ELEMENTARY SCHOOL" },
    { id: 19, value: "PANGHULO ELEMENTARY SCHOOL" },
    { id: 20, value: "PANGHULO ELEMENTARY SCHOOL I" },
    { id: 21, value: "POTRERO ELEMENTARY SCHOOL" },
    { id: 22, value: "POTRERO ELEMENTARY SCHOOL I" },
    { id: 23, value: "SANTIAGO SYJUCO MES" },
    { id: 24, value: "SANTULAN ELEMENTARY SCHOOL" },
    { id: 25, value: "TAÑONG ELEMENTARY SCHOOL I" },
    { id: 26, value: "TAÑONG INTEGRATED SCHOOL" },
    { id: 27, value: "TINAJEROS ELEMENTARY SCHOOL" },
    { id: 28, value: "TONSUYA ELEMENTARY SCHOOL" },
    { id: 29, value: "ACACIA NATL HIGH SCHOOL JHS" },
    { id: 30, value: "CATMON INTEGRATED SCHOOL JHS" },
    { id: 31, value: "COL RAMON CAMUS INTEGRATED SCHOOL JHS" },
    { id: 32, value: "CONCEPCION TVS" },
    { id: 33, value: "DAMPALIT IS" },
    { id: 34, value: "IMELDA ISS" },
    { id: 35, value: "LONGOS NHS" },
    { id: 36, value: "MALABON CITY SCIENCE & MATHEMATICS NHS" },
    { id: 37, value: "MALABON NHS" },
    { id: 38, value: "PANGHULO NHS" },
    { id: 39, value: "POTRERO NHS" },
    { id: 40, value: "SANTIAGO SYJUCO MISS" },
    { id: 41, value: "TAÑONG IS" },
    { id: 42, value: "TAÑONG NHS" },
    { id: 43, value: "TINAJEROS NHS" },
    { id: 44, value: "TUGATOG NHS" },
    { id: 45, value: "MALABON CITY TECH VOC AND ENTREPRENEURSHIP SHS" },
    { id: 46, value: "MALABON NATL HIGH SCHOOL SHS" },
    { id: 47, value: "NINOY AQUINO SENIOR HIGH SCHOOL" },
];


export const schools_classifications = [
    { id: 1, value: "Teaching" },
    { id: 2, value: "Non-Teaching" },
    { id: 3, value: "Related Teaching" }
];


export const school_hours = [
    { id: 1, value: "4 hours" },
    { id: 2, value: "5 hours" },
    { id: 3, value: "6 hours" },
    { id: 4, value: "7 hours" },
    { id: 5, value: "8 hours" },
    { id: 6, value: "12 hours" },
    { id: 7, value: "16 hours" },
    { id: 8, value: "20 hours" },
    { id: 9, value: "24 hours" },
    { id: 10, value: "28 hours" },
    { id: 11, value: "32 hours" },
    { id: 12, value: "36 hours" },
    { id: 13, value: "40 hours" },
    { id: 14, value: "44 hours" },
    { id: 15, value: "48 hours" },
    { id: 16, value: "52 hours" },
    { id: 17, value: "56 hours" },
    { id: 18, value: "60 hours" },
    { id: 19, value: "64 hours" },
    { id: 20, value: "68 hours" },
    { id: 21, value: "72 hours" },
    { id: 22, value: "76 hours" },
    { id: 23, value: "80 hours" },
    { id: 24, value: "84 hours" },
    { id: 25, value: "88 hours" },
    { id: 26, value: "92 hours" },
    { id: 27, value: "96 hours" },
    { id: 28, value: "100 hours" },
    { id: 29, value: "104 hours" },
    { id: 30, value: "108 hours" },
    { id: 31, value: "112 hours" },
    { id: 32, value: "116 hours" },
    { id: 33, value: "120 hours" },
];


export const school_years_in_service = [
    { id: 1, value: '1' },
    { id: 2, value: '2' },
    { id: 3, value: '3' },
    { id: 4, value: '4' },
    { id: 5, value: '5' },
    { id: 6, value: '6' },
    { id: 7, value: '7' },
    { id: 8, value: '8' },
    { id: 9, value: '9' },
    { id: 10, value: '10' },
    { id: 11, value: '11' },
    { id: 12, value: '12' },
    { id: 13, value: '13' },
    { id: 14, value: '14' },
    { id: 15, value: '15' },
    { id: 16, value: '16' },
    { id: 17, value: '17' },
    { id: 18, value: '18' },
    { id: 19, value: '19' },
    { id: 20, value: '20' },
    { id: 21, value: '21' },
    { id: 22, value: '22' },
    { id: 23, value: '23' },
    { id: 24, value: '24' },
    { id: 25, value: '25' },
    { id: 26, value: '26' },
    { id: 27, value: '27' },
    { id: 28, value: '28' },
    { id: 29, value: '29' },
    { id: 30, value: '30' },
    { id: 31, value: '31' },
    { id: 32, value: '32' },
    { id: 33, value: '33' },
    { id: 34, value: '34' },
    { id: 35, value: '35' },
    { id: 36, value: '36' },
    { id: 37, value: '37' },
    { id: 38, value: '38' },
    { id: 39, value: '39' },
    { id: 40, value: '40' }
];



export const school_year = [
    { id: 1, value: '2022' },
    { id: 2, value: '2021' },
    { id: 3, value: '2020' },
    { id: 4, value: '2019' }
];
